// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace JobApplications.Entity.Models
{
    public partial class Applicant_Details
    {
        public int Applicant_Id { get; set; }
        public string Applicant_Full_Name { get; set; }
        public string Applicant_Gender { get; set; }
        public string Applicant_Email { get; set; }
        public int Applicant_Age { get; set; }
        public string Applicant_Location { get; set; }
        public string Applicant_file { get; set; }
        public string Name { get; set; }
        public int Applicant_10th_Mark { get; set; }
        public int Applicant_12th_Mark { get; set; }
        public int Applicant_CGPA { get; set; }
        public string Applicant_Interest { get; set; }
        public string Applicant_Skills { get; set; }
        public bool Is_Deleted { get; set; }
        public DateTime Created_Time_Stamp { get; set; }
        public DateTime Updaed_Time_Stamp { get; set; }
    }
}